In [25]:
%%markdown
# Wstęp do uczenia maszynowego

# Wstęp do uczenia maszynowego


In [26]:
%%markdown
## Laboratorium 1.
1) utwórz tablicę zawierającą 10 zer\
2) utwórz tablicę zawierającą 10 piątek\
3) utwórz tablicę zawierającą liczby od 10 do 50\
4) utwórz macierz (tablica wielowymiarowa) o wymiarach 3x3 zawierającą liczby od 0 do 8\
5) utwórz macierz jednostkową o wymiarach 3x3 \
6) utwórz macierz o wymiarach 5x5 zawierającą liczby z dystrybucji normalnej (Gaussa)\
7) utwórz macierz o wymiarach 10x10 zawierającą liczby od 0,01 do 1 z krokiem 0,01\
8) utwórz tablicę zawierającą 20 liniowo rozłożonych liczb między 0 a 1 (włącznie z 0 i 1)\
9) utwórz tablicę zawierającą losowe liczby z przedziału (1, 25), następnie zamień ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami:\
&nbsp;&nbsp;9.1) oblicz sumę wszystkich liczb w ww. macierzy\
&nbsp;&nbsp;9.2) oblicz średnią wszystkich liczb w ww. macierzy\
&nbsp;&nbsp;9.3) oblicz standardową dewiację dla liczb w ww. macierzy\
&nbsp;&nbsp;9.4) oblicz sumę każdej kolumny ww. macierzy i zapisz ją do tablicy \
10) utwórz macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100):\
&nbsp;&nbsp;10.1) oblicz medianę tych liczb\
&nbsp;&nbsp;10.2) znajdź najmniejszą liczbę tej macierzy\
&nbsp;&nbsp;10.3) znajdź największą liczbę tej macierzy\
11) utwórz macierz o wymiarach różnych od siebie i większych od 1, zawierającą losowe liczby z przedziału (0, 100) i dokonaj jej transpozycji\
12) utwórz dwie macierze o odpowiednich wymiarach (doczytać), większych od 2 i dodaj je do siebie\
13) utwórz dwie macierze o odpowiednich wymiarach (doczytać) różnych od siebie i większych od 2, a następnie pomnóż je przez siebie za pomocą dwóch różnych funkcji (np. ‘matmul’ i ‘multiply’)

## Laboratorium 1.
1) utwórz tablicę zawierającą 10 zer\
2) utwórz tablicę zawierającą 10 piątek\
3) utwórz tablicę zawierającą liczby od 10 do 50\
4) utwórz macierz (tablica wielowymiarowa) o wymiarach 3x3 zawierającą liczby od 0 do 8\
5) utwórz macierz jednostkową o wymiarach 3x3 \
6) utwórz macierz o wymiarach 5x5 zawierającą liczby z dystrybucji normalnej (Gaussa)\
7) utwórz macierz o wymiarach 10x10 zawierającą liczby od 0,01 do 1 z krokiem 0,01\
8) utwórz tablicę zawierającą 20 liniowo rozłożonych liczb między 0 a 1 (włącznie z 0 i 1)\
9) utwórz tablicę zawierającą losowe liczby z przedziału (1, 25), następnie zamień ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami:\
&nbsp;&nbsp;9.1) oblicz sumę wszystkich liczb w ww. macierzy\
&nbsp;&nbsp;9.2) oblicz średnią wszystkich liczb w ww. macierzy\
&nbsp;&nbsp;9.3) oblicz standardową dewiację dla liczb w ww. macierzy\
&nbsp;&nbsp;9.4) oblicz sumę każdej kolumny ww. macierzy i zapisz ją do tablicy \
10) utwórz macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100):\
&nbsp;&nbsp;10.1) oblicz medianę tych liczb\
&nbsp;&nbsp;10.2) znajdź najmniejszą liczbę tej macierzy\
&nbsp;&nbsp;10.3) znajdź największą liczbę tej macierzy\
11) utwórz macierz o wymiarach różnych od siebie i większych od 1, zawierającą losowe liczby z przedziału (0, 100) i dokonaj jej transpozycji\
12) utwórz dwie macierze o odpowiednich wymiarach (doczytać), większych od 2 i dodaj je do siebie\
13) utwórz dwie macierze o odpowiednich wymiarach (doczytać) różnych od siebie i większych od 2, a następnie pomnóż je przez siebie za pomocą dwóch różnych funkcji (np. ‘matmul’ i ‘multiply’)


In [27]:
import numpy as np
print('1)')
m=np.zeros(10)
print(m)

1)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
print('2)')
m=np.full(10,5)
print(m)

2)
[5 5 5 5 5 5 5 5 5 5]


In [29]:
print('3)')
m=np.arange(10,50)
print(m)

3)
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [30]:
print('4)')
m=np.arange(0,9).reshape(3,3)
print(m)

4)
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
print('5)')
m=np.eye(3,3)
print(m)

5)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
print('6)')
m=np.random.normal(0,1,25).reshape(5,5)
print(m)

6)
[[ 0.77216512  0.03101491  0.33963927 -0.77015456  1.36978137]
 [-1.36054688 -0.53712672 -0.36319281 -0.01145843  0.55204301]
 [ 0.3808432  -1.63313332 -1.06780758  0.92635694 -1.1487619 ]
 [ 2.30587381 -2.05177389  1.64835481 -1.34469776 -0.42314463]
 [-2.20885951 -1.86856118 -1.88233787 -0.31842439  0.47070656]]


In [33]:
print('7)')
m=np.arange(0.00,1,0.01).reshape(10,10)
print(m)

7)
[[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]
 [0.1  0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19]
 [0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29]
 [0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39]
 [0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79]
 [0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89]
 [0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99]]


In [34]:
print('8)')
m=np.arange(0,1.0,1/20)
print(m)

8)
[0.   0.05 0.1  0.15 0.2  0.25 0.3  0.35 0.4  0.45 0.5  0.55 0.6  0.65
 0.7  0.75 0.8  0.85 0.9  0.95]


print('9)')
m=np.random.uniform(1,25,25).reshape(5,5)
print(i)
print('9.1)\n')
print(np.sum(m))
print('9.2)\n')
print(np.average(m))
print('9.3)\n')
print(np.std(m))
print('9.4)\n')
print(np.sum(i,axis=1))

In [35]:
print('9)')
m=np.random.uniform(0,100,25).reshape(5,5)
print(m)
print('9.1)\n')
print(np.median(m))
print('9.2)\n')
print(np.min(m))
print('9.3\n')
print(np.max(m))

9)
[[17.01955448 73.05199713 37.85976829 58.72283075 60.4345757 ]
 [18.72473397 20.81384279 61.14394445 48.1507547  41.62921397]
 [ 8.94956905  3.73725406 24.33835288 30.68878771  6.06781206]
 [ 1.51494561 43.53542087 73.41502773 90.11012744 10.86750258]
 [82.90475275 53.87590635 22.00931427 26.08099218 94.9641632 ]]
9.1)

37.85976829486516
9.2)

1.5149456129518568
9.3

94.96416319524091


In [36]:
print('10)')
k=np.random.uniform(0,100,20).reshape(5,4)
print(k)
print('\n')
k=np.transpose(k)
print(k)

10)
[[ 3.56363447 73.85346811 89.37174552 57.87243995]
 [70.49509356 74.64484409 59.20537078 90.6028677 ]
 [89.13966667 98.42162485 91.35651184 73.02886099]
 [ 6.95812428 43.81086377  5.63876231 41.98638933]
 [35.59132821 54.77775889 86.59102975 92.93957989]]


[[ 3.56363447 70.49509356 89.13966667  6.95812428 35.59132821]
 [73.85346811 74.64484409 98.42162485 43.81086377 54.77775889]
 [89.37174552 59.20537078 91.35651184  5.63876231 86.59102975]
 [57.87243995 90.6028677  73.02886099 41.98638933 92.93957989]]


In [37]:
print('11)')
l=np.random.uniform(0,100,25).reshape(5,5)
m=np.random.uniform(0,100,25).reshape(5,5)
print(l)
print('\n')
print(m)
n=np.add(l,m)
print('\n')
print(n)

11)
[[89.47819305 61.03378164 41.7591305  14.99695721 91.28708059]
 [28.06402778 41.37060416 30.71088799 25.25919621 80.59879564]
 [10.07152784 55.12286265 61.25239833 37.4213735  46.60652382]
 [60.021831   27.26654404 96.27610273 88.32483841 89.04072246]
 [ 5.28217575 96.53053142 90.14651148 73.77084424 37.36910279]]


[[87.32521253 49.72659496 74.66003529 36.80226861 85.86580175]
 [15.95490863 57.98557008 49.72592229 40.54120273 10.42433312]
 [55.69913267 99.56106288 38.05616909 82.26498652 81.98010959]
 [ 3.63101471 80.27606876 29.06984631 25.12981716 53.65139268]
 [45.43064405 84.75263511 36.34752544 55.31752199 17.61028771]]


[[176.80340559 110.7603766  116.41916578  51.79922582 177.15288234]
 [ 44.01893642  99.35617424  80.43681028  65.80039894  91.02312876]
 [ 65.77066052 154.68392553  99.30856742 119.68636001 128.58663342]
 [ 63.65284571 107.54261281 125.34594904 113.45465557 142.69211514]
 [ 50.7128198  181.28316653 126.49403693 129.08836623  54.9793905 ]]


In [38]:
print('12)')
o=np.random.uniform(0,100,10).reshape(2,5)
print(o)
print('\n')
p=np.random.uniform(0,100,10).reshape(5,2)
print(p)
print('\n')
q=np.matmul(o,p)
print(q)
print('\n')
r=np.multiply(p,3)
print(r)

12)
[[70.44602046 64.02522023 17.98407127 29.69166184 74.9513113 ]
 [74.53427593 67.48015862 57.04130583 73.99201105 64.63396316]]


[[ 4.28360272 32.35221989]
 [16.7439558  12.07050962]
 [87.50230845 42.56905004]
 [99.33185887 35.48183608]
 [58.84172768  0.41276497]]


[[10307.03858604  4901.91896456]
 [17593.34401544  8306.114433  ]]


[[ 12.85080817  97.05665967]
 [ 50.23186739  36.21152885]
 [262.50692536 127.70715012]
 [297.99557662 106.44550824]
 [176.52518304   1.2382949 ]]
